### ISSUE TITLE
Installation is completely broken (at least on Android 12)

### ISSUE THREAD

**Issue by daemonspudguy** [Magisk-Modules-Repo/ccbins#6] opened 2021-10-29 21:52 UTC
It fails at testing Internet connection, and here is a log.
[magisk_install_log_2021-10-29T17_51_05Z.log](https://github.com/Magisk-Modules-Repo/ccbins/files/7445071/magisk_install_log_2021-10-29T17_51_05Z.log)

**Comment by Zackptg5** [comment] 2021-10-29 23:48
Worked fine until 12? I'll see if I can fire up an emulator for a12 and test it out

**Comment by daemonspudguy** [comment] 2021-10-30 02:15
Yep, I'm on canary. But when I was running stable Magisk it was just as broken.

**Comment by Zackptg5** [comment] 2021-10-30 03:42
Definitely some things changed, likely in magisk variables/structure. I'll figure out a fix and hopefully get it done next week

**Comment by Zackptg5** [comment] 2021-10-30 04:18
So I can't get internet to work in the emulator at all when in adb so I don't have a way to test it currently :/

**Comment by daemonspudguy** [comment] 2021-10-30 19:24
What phone do you have? You might be able to test on an Android 12 GSI that's been rooted.

**Comment by Zackptg5** [comment] 2021-10-30 22:13
OP8 is my dev phone

**Comment by Zackptg5** [comment] 2021-11-02 18:49
Just bought the pixel 5a so I'll have an a12 dev phone. Will be a week or so before it arrives and likely a bit longer before I have the chance to set it up and start testing on it

**Comment by Zackptg5** [comment] 2021-11-11 21:34
Looks like the problem is with static curl - doesn't resolve dns on A12. I'll update this once I figure out a fix

**Comment by Zackptg5** [comment] 2021-11-12 01:37
Pushed fix, should be good to go

**Closed by Zackptg5** 2021-11-12 01:37 UTC
Labels: bug
